server:
  port: 8090
spring:
  application:
    name: gov-gateway
    main:
      web-application-type: reactive
  config:
    import:
      - optional:nacos:gateway-routes.yaml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: ${GOV_NACOS_ADDR:127.0.0.1:8848}
        username: ${GOV_NACOS_USERNAME:nacos}
        password: ${GOV_NACOS_PASSWORD:7PkhQ0b92nUU}
      config:
        server-addr: ${GOV_NACOS_ADDR:127.0.0.1:8848}
        username: ${GOV_NACOS_USERNAME:nacos}
        password: ${GOV_NACOS_PASSWORD:7PkhQ0b92nUU}
        file-extension: yaml
        refresh-enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
  data:
    redis:
      host: ${GOV_REDIS_HOST:127.0.0.1}
      port: ${GOV_REDIS_PORT:6379}
      password: ${GOV_REDIS_PASSWORD:}
gov:
  jwt:
    secret: ${GOV_JWT_SECRET:gov-micro-demo-secret-key-2026-very-long-for-hs256}
gateway:
  auth:
    white-list:
      - /api/auth/login
      - /api/license/verify/**