server:
  port: 8081

spring:
  application:
    name: gov-auth
  datasource:
    url: ${GOV_DB_URL:jdbc:mysql://127.0.0.1:3306/gov_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${GOV_DB_USERNAME:root}
    password: ${GOV_DB_PASSWORD:root123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: ${GOV_NACOS_ADDR:127.0.0.1:8848}
        username: ${GOV_NACOS_USERNAME:nacos}
        password: ${GOV_NACOS_PASSWORD:7PkhQ0b92nUU}

gov:
  jwt:
    secret: ${GOV_JWT_SECRET:gov-micro-demo-secret-key-2026-very-long-for-hs256}
    expire: 43200


knife4j:
  enable: true
  setting:
    language: zh_cn